### ISSUE TITLE
Fatal error: Class 'PHPUnit_Framework_TestSuite' not found

### ISSUE THREAD

**Issue by tgajewski007** [piece/makegood#70]
Its always show when makegood starts test 
my config 
Eclipse Java Luna R (not SR1)  + PDT 3.3.1 + subclipse 1.10 + MakeGood 3.1.1
xampp 1.8.3 (+ Oracle Instant client library and enabled php_oci)

all fresh install 

full  trace 

Fatal error: Class 'PHPUnit_Framework_TestSuite' not found in E:\Program Files\eclipse.luna\plugins\com.piece_framework.makegood.stagehandtestrunner_3.1.1.v201409021510\resources\php\vendor\piece\stagehand-testrunner\src\Collector\PHPUnitCollector.php on line 124

Call Stack:
    0.0010     150088   1. {main}() E:\Program Files\eclipse.luna\plugins\com.piece_framework.makegood.stagehandtestrunner_3.1.1.v201409021510\resources\php\bin\testrunner.php:0
    0.3970    1770008   2. Symfony\Component\Console\Application->run($input = ???, $output = ???) E:\Program Files\eclipse.luna\plugins\com.piece_framework.makegood.stagehandtestrunner_3.1.1.v201409021510\resources\php\bin\testrunner.php:55
    0.4390    2027672   3. Symfony\Component\Console\Application->doRun($input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = array (0 => '--no-ansi', 1 => 'phpunit', 2 => '--log-junit=C:\Users\tomek\AppData\Local\Temp\com.piece_framework.makegood.launch\MakeGood1414694884162.xml', 3 => '--log-junit-realtime', 4 => '-R', 5 => '--test-file-pattern=Test(?:Case)?\.php$', 6 => 'O:/wwwroot/EnMarket/UnitTests'); private $parsed = array (); protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = array (...); private $requiredCount = 1; private $hasAnArrayArgument = TRUE; private $hasOptional = TRUE; private $options = array (...); private $shortcuts = array (...) }; protected $options = array ('no-ansi' => TRUE, 'log-junit' => 'C:\Users\tomek\AppData\Local\Temp\com.piece_framework.makegood.launch\MakeGood1414694884162.xml', 'log-junit-realtime' => TRUE, 'recursive' => TRUE, 'test-file-pattern' => 'Test(?:Case)?\.php$'); protected $arguments = array ('command' => 'phpunit', 'test_directory_or_file' => array (...)); protected $interactive = TRUE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(88) of type (stream); private ${Symfony\Component\Console\Output\Output}:verbosity = 1; private ${Symfony\Component\Console\Output\Output}:formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private ${Symfony\Component\Console\Output\StreamOutput}:stream = resource(82) of type (stream); private ${Symfony\Component\Console\Output\Output}:verbosity = 1; private ${Symfony\Component\Console\Output\Output}:formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = FALSE; private $styles = array (...); private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) E:\Program Files\eclipse.luna\plugins\com.piece_framework.makegood.stagehandtestrunner_3.1.1.v201409021510\resources\php\vendor\symfony\console\Symfony\Component\Console\Application.php:124
    0.4400    2028200   4. Symfony\Component\Console\Application->doRunCommand($command = class Stagehand\TestRunner\CLI\TestRunnerApplication\Command\PHPUnitCommand { protected $fileSystem = class Stagehand\TestRunner\Util\FileSystem {  }; private ${Symfony\Component\Console\Command\Command}:application = class Stagehand\TestRunner\CLI\TestRunnerApplication\Application { protected $commandRepository = class Stagehand\TestRunner\CLI\TestRunnerApplication\Command\CommandRepository { ... }; private ${Symfony\Component\Console\Application}:commands = array (...); private ${Symfony\Component\Console\Application}:wantHelps = FALSE; private ${Symfony\Component\Console\Application}:runningCommand = ...; private ${Symfony\Component\Console\Application}:name = 'Stagehand_TestRunner'; private ${Symfony\Component\Console\Application}:version = '4.0.0'; private ${Symfony\Component\Console\Application}:catchExceptions = TRUE; private ${Symfony\Component\Console\Application}:autoExit = FALSE; private ${Symfony\Component\Console\Application}:definition = class Symfony\Component\Console\Input\InputDefinition { ... }; private ${Symfony\Component\Console\Application}:helperSet = class Symfony\Component\Console\Helper\HelperSet { ... }; private ${Symfony\Component\Console\Application}:dispatcher = NULL; private ${Symfony\Component\Console\Application}:terminalDimensions = NULL; private ${Symfony\Component\Console\Application}:defaultCommand = 'list' }; private ${Symfony\Component\Console\Command\Command}:name = 'phpunit'; private ${Symfony\Component\Console\Command\Command}:processTitle = NULL; private ${Symfony\Component\Console\Command\Command}:aliases = array (); private ${Symfony\Component\Console\Command\Command}:definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = array (...); private $requiredCount = 1; private $hasAnArrayArgument = TRUE; private $hasOptional = TRUE; private $options = array (...); private $shortcuts = array (...) }; private ${Symfony\Component\Console\Command\Command}:help = 'The <info>phpunit</info> command runs tests with PHPUnit:\r\n\r\n  <info>testrunner phpunit ...</info>'; private ${Symfony\Component\Console\Command\Command}:description = 'Runs tests with PHPUnit.'; private ${Symfony\Component\Console\Command\Command}:ignoreValidationErrors = FALSE; private ${Symfony\Component\Console\Command\Command}:applicationDefinitionMerged = TRUE; private ${Symfony\Component\Console\Command\Command}:applicationDefinitionMergedWithArgs = TRUE; private ${Symfony\Component\Console\Command\Command}:code = NULL; private ${Symfony\Component\Console\Command\Command}:synopsis = 'phpunit [-p|--preload-script="..."] [-c|--config="..."] [-R|--recursive] [-a|--autotest] [-w|--watch-dir="..."] [-m|--notify] [-d|--detailed-progress] [-s|--stop-on-failure] [--log-junit="..."] [--log-junit-realtime] [--test-file-pattern="..."] [--test-method="..."] [--test-class="..."] [--phpunit-config="..."] [test_directory_or_file1] ... [test_directory_or_fileN]'; private ${Symfony\Component\Console\Command\Command}:helperSet = class Symfony\Component\Console\Helper\HelperSet { private $helpers = array (...); private $command = NULL } }, $input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = array (0 => '--no-ansi', 1 => 'phpunit', 2 => '--log-junit=C:\Users\tomek\AppData\Local\Temp\com.piece_framework.makegood.launch\MakeGood1414694884162.xml', 3 => '--log-junit-realtime', 4 => '-R', 5 => '--test-file-pattern=Test(?:Case)?\.php$', 6 => 'O:/wwwroot/EnMarket/UnitTests'); private $parsed = array (); protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = array (...); private $requiredCount = 1; private $hasAnArrayArgument = TRUE; private $hasOptional = TRUE; private $options = array (...); private $shortcuts = array (...) }; protected $options = array ('no-ansi' => TRUE, 'log-junit' => 'C:\Users\tomek\AppData\Local\Temp\com.piece_framework.makegood.launch\MakeGood1414694884162.xml', 'log-junit-realtime' => TRUE, 'recursive' => TRUE, 'test-file-pattern' => 'Test(?:Case)?\.php$'); protected $arguments = array ('command' => 'phpunit', 'test_directory_or_file' => array (...)); protected $interactive = TRUE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(88) of type (stream); private ${Symfony\Component\Console\Output\Output}:verbosity = 1; private ${Symfony\Component\Console\Output\Output}:formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private ${Symfony\Component\Console\Output\StreamOutput}:stream = resource(82) of type (stream); private ${Symfony\Component\Console\Output\Output}:verbosity = 1; private ${Symfony\Component\Console\Output\Output}:formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = FALSE; private $styles = array (...); private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) E:\Program Files\eclipse.luna\plugins\com.piece_framework.makegood.stagehandtestrunner_3.1.1.v201409021510\resources\php\vendor\symfony\console\Symfony\Component\Console\Application.php:193
    0.4400    2028408   5. Symfony\Component\Console\Command\Command->run($input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = array (0 => '--no-ansi', 1 => 'phpunit', 2 => '--log-junit=C:\Users\tomek\AppData\Local\Temp\com.piece_framework.makegood.launch\MakeGood1414694884162.xml', 3 => '--log-junit-realtime', 4 => '-R', 5 => '--test-file-pattern=Test(?:Case)?\.php$', 6 => 'O:/wwwroot/EnMarket/UnitTests'); private $parsed = array (); protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = array (...); private $requiredCount = 1; private $hasAnArrayArgument = TRUE; private $hasOptional = TRUE; private $options = array (...); private $shortcuts = array (...) }; protected $options = array ('no-ansi' => TRUE, 'log-junit' => 'C:\Users\tomek\AppData\Local\Temp\com.piece_framework.makegood.launch\MakeGood1414694884162.xml', 'log-junit-realtime' => TRUE, 'recursive' => TRUE, 'test-file-pattern' => 'Test(?:Case)?\.php$'); protected $arguments = array ('command' => 'phpunit', 'test_directory_or_file' => array (...)); protected $interactive = TRUE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(88) of type (stream); private ${Symfony\Component\Console\Output\Output}:verbosity = 1; private ${Symfony\Component\Console\Output\Output}:formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private ${Symfony\Component\Console\Output\StreamOutput}:stream = resource(82) of type (stream); private ${Symfony\Component\Console\Output\Output}:verbosity = 1; private ${Symfony\Component\Console\Output\Output}:formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = FALSE; private $styles = array (...); private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) E:\Program Files\eclipse.luna\plugins\com.piece_framework.makegood.stagehandtestrunner_3.1.1.v201409021510\resources\php\vendor\symfony\console\Symfony\Component\Console\Application.php:887
    0.4440    2031656   6. Stagehand\TestRunner\CLI\TestRunnerApplication\Command\PluginCommand->execute($input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = array (0 => '--no-ansi', 1 => 'phpunit', 2 => '--log-junit=C:\Users\tomek\AppData\Local\Temp\com.piece_framework.makegood.launch\MakeGood1414694884162.xml', 3 => '--log-junit-realtime', 4 => '-R', 5 => '--test-file-pattern=Test(?:Case)?\.php$', 6 => 'O:/wwwroot/EnMarket/UnitTests'); private $parsed = array (); protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = array (...); private $requiredCount = 1; private $hasAnArrayArgument = TRUE; private $hasOptional = TRUE; private $options = array (...); private $shortcuts = array (...) }; protected $options = array ('no-ansi' => TRUE, 'log-junit' => 'C:\Users\tomek\AppData\Local\Temp\com.piece_framework.makegood.launch\MakeGood1414694884162.xml', 'log-junit-realtime' => TRUE, 'recursive' => TRUE, 'test-file-pattern' => 'Test(?:Case)?\.php$'); protected $arguments = array ('command' => 'phpunit', 'test_directory_or_file' => array (...)); protected $interactive = TRUE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(88) of type (stream); private ${Symfony\Component\Console\Output\Output}:verbosity = 1; private ${Symfony\Component\Console\Output\Output}:formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private ${Symfony\Component\Console\Output\StreamOutput}:stream = resource(82) of type (stream); private ${Symfony\Component\Console\Output\Output}:verbosity = 1; private ${Symfony\Component\Console\Output\Output}:formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = FALSE; private $styles = array (...); private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) E:\Program Files\eclipse.luna\plugins\com.piece_framework.makegood.stagehandtestrunner_3.1.1.v201409021510\resources\php\vendor\symfony\console\Symfony\Component\Console\Command\Command.php:252
    0.5780    2876272   7. Stagehand\TestRunner\CLI\TestRunnerApplication\Command\PluginCommand->createTestRunner($continuousTesting = FALSE) E:\Program Files\eclipse.luna\plugins\com.piece_framework.makegood.stagehandtestrunner_3.1.1.v201409021510\resources\php\vendor\piece\stagehand-testrunner\src\CLI\TestRunnerApplication\Command\PluginCommand.php:149
    0.5780    2876352   8. Stagehand\TestRunner\Core\ApplicationContext->createComponent($componentID = 'test_runner') E:\Program Files\eclipse.luna\plugins\com.piece_framework.makegood.stagehandtestrunner_3.1.1.v201409021510\resources\php\vendor\piece\stagehand-testrunner\src\CLI\TestRunnerApplication\Command\PluginCommand.php:295
    0.5780    2876384   9. Stagehand\ComponentFactory\ComponentFactory->create($componentID = 'test_runner', $external = ???) E:\Program Files\eclipse.luna\plugins\com.piece_framework.makegood.stagehandtestrunner_3.1.1.v201409021510\resources\php\vendor\piece\stagehand-testrunner\src\Core\ApplicationContext.php:104
    0.5780    2876648  10. Symfony\Component\DependencyInjection\Container->get($id = 'test_runner', $invalidBehavior = ???) E:\Program Files\eclipse.luna\plugins\com.piece_framework.makegood.stagehandtestrunner_3.1.1.v201409021510\resources\php\vendor\piece\stagehand-componentfactory\src\Stagehand\ComponentFactory\ComponentFactory.php:76
    0.5780    2876992  11. Stagehand\TestRunner\DependencyInjection\PHPUnitContainer->getTestRunnerService() E:\Program Files\eclipse.luna\plugins\com.piece_framework.makegood.stagehandtestrunner_3.1.1.v201409021510\resources\php\vendor\symfony\dependency-injection\Symfony\Component\DependencyInjection\Container.php:312
    0.5870    2920008  12. Symfony\Component\DependencyInjection\Container->get($id = 'phpunit.collector', $invalidBehavior = ???) E:\Program Files\eclipse.luna\plugins\com.piece_framework.makegood.stagehandtestrunner_3.1.1.v201409021510\resources\php\vendor\piece\stagehand-testrunner\src\DependencyInjection\PHPUnitContainer.php:448
    0.5870    2920328  13. Stagehand\TestRunner\DependencyInjection\PHPUnitContainer->getPhpunit_CollectorService() E:\Program Files\eclipse.luna\plugins\com.piece_framework.makegood.stagehandtestrunner_3.1.1.v201409021510\resources\php\vendor\symfony\dependency-injection\Symfony\Component\DependencyInjection\Container.php:312
    0.5920    3003552  14. Stagehand\TestRunner\Collector\Collector->__construct($testTargetRepository = class Stagehand\TestRunner\Core\TestTargetRepository { protected $plugin = class Stagehand\TestRunner\Core\Plugin\PHPUnitPlugin { protected $features = array (...) }; protected $resources = array (0 => 'O:/wwwroot/EnMarket/UnitTests'); protected $methods = array (); protected $classes = array (); protected $filePattern = 'Test(?:Case)?\.php$' }) E:\Program Files\eclipse.luna\plugins\com.piece_framework.makegood.stagehandtestrunner_3.1.1.v201409021510\resources\php\vendor\piece\stagehand-testrunner\src\DependencyInjection\PHPUnitContainer.php:302
    0.5920    3003632  15. Stagehand\TestRunner\Collector\PHPUnitCollector->createTestSuite($name = 'The test suite generated by Stagehand_TestRunner') E:\Program Files\eclipse.luna\plugins\com.piece_framework.makegood.stagehandtestrunner_3.1.1.v201409021510\resources\php\vendor\piece\stagehand-testrunner\src\Collector\Collector.php:92

Variables in local scope (#15):
  $name = 'The test suite generated by Stagehand_TestRunner'

**Comment by heik** [comment]
Hi,

i am running into problems when using the @runInSeparateProcess annotation in combination with the "Preload Script" - my autoloader seems to be loaded only, when starting a bunch of tests, but not for the separate processes :(

Am i missing something or might this be a feature request?
